SELECT PRODUCT_NAME, QUANTITY_ON_HAND, WAREHOUSE_NAME
FROM PRODUCT_INFORMATION JOIN INVENTORIES
ON  PRODUCT_INFORMATION.PRODUCT_ID = INVENTORIES.PRODUCT_ID
JOIN WAREHOUSES
ON INVENTORIES.WAREHOUSE_ID = WAREHOUSES.WAREHOUSE_ID
ORDER BY QUANTITY_ON_HAND DESC;
