SELECT COUNTRY_NAME ,COUNT (CUST_ID)
FROM COUNTRIES JOIN CUSTOMERS
ON COUNTRIES.COUNTRY_ID = CUSTOMERS.COUNTRY_ID
WHERE  SUBSTR (COUNTRY_NAME,1,1) IN ('A','B','C','D','P','T')
GROUP BY COUNTRY_NAME
HAVING COUNT(CUST_ID)>15
ORDER BY COUNTRY_NAME ASC;