SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.QUANTITY)
FROM ORDER_ITEMS O
JOIN PRODUCT_INFORMATION P
ON (O.PRODUCT_ID = P.PRODUCT_ID)
GROUP BY O.PRODUCT_ID,P.PRODUCT_NAME
HAVING SUM(O.QUANTITY) > 200
UNION
SELECT O.PRODUCT_ID, TO_CHAR(NULL) "UNKNOWN", SUM(O.QUANTITY)
FROM ORDER_ITEMS O
GROUP BY O.PRODUCT_ID
HAVING SUM(O.QUANTITY) > 1800;
