SELECT CUST_ID, TIME_ID, AMOUNT_SOLD
FROM SALES
WHERE TIME_ID = '01-JAN-98' AND AMOUNT_SOLD > 4000
UNION
SELECT CUST_ID, TIME_ID, AMOUNT_SOLD
FROM SALES
WHERE TIME_ID = '02-JAN-98' AND CUST_ID IN(
  SELECT CUST_ID
  FROM SALES
  WHERE TIME_ID = '01-JAN-98' AND AMOUNT_SOLD > 4000
)
ORDER BY 1,2,3 DESC;