SELECT PROD_ID,MAX(UNIT_COST)
FROM COSTS
WHERE UNIT_PRICE > 10
GROUP BY PROD_ID
HAVING MAX(UNIT_COST)>10;
-- 
SELECT PROD_ID, MIN(TIME_ID), 'MIN'
FROM COSTS
WHERE (PROD_ID, UNIT_COST) IN(
  SELECT PROD_ID,MAX(UNIT_COST)
  FROM COSTS
  WHERE UNIT_PRICE > 10
  GROUP BY PROD_ID
  HAVING MAX(UNIT_COST)>10)
GROUP BY PROD_ID
UNION 
SELECT PROD_ID, MAX(TIME_ID), 'MAX'
FROM COSTS
WHERE (PROD_ID, UNIT_COST) IN(
  SELECT PROD_ID,MAX(UNIT_COST)
  FROM COSTS
  WHERE UNIT_PRICE > 10
  GROUP BY PROD_ID
  HAVING MAX(UNIT_COST)>10)
GROUP BY PROD_ID
ORDER BY 1,2;
