SELECT A.PROD_ID, PRODUCTS.PROD_NAME 
FROM (
  SELECT PROD_ID, MIN(TIME_ID)
  FROM COSTS
  WHERE (PROD_ID, UNIT_COST) IN(
    SELECT PROD_ID,MAX(UNIT_COST)
    FROM COSTS
    WHERE UNIT_PRICE > 10
    GROUP BY PROD_ID
    HAVING MAX(UNIT_COST)>10)
  GROUP BY PROD_ID
  INTERSECT
  SELECT PROD_ID, MAX(TIME_ID)
  FROM COSTS
  WHERE (PROD_ID, UNIT_COST) IN(
    SELECT PROD_ID,MAX(UNIT_COST)
    FROM COSTS
    WHERE UNIT_PRICE > 10
    GROUP BY PROD_ID
    HAVING MAX(UNIT_COST)>10)
  GROUP BY PROD_ID 
  ) A
  -- DA SE DOVYRSHI
  OUTER JOIN PRODUCTS 
ON PRODUCTS.PROD_ID = A.PROD_ID
  
ORDER BY 1;