SELECT PROMO_NAME, PROMO_CATEGORY, PROMO_BEGIN_DATE, PROMO_END_DATE, PROMO_COST
FROM PROMOTIONS
WHERE (PROMO_COST >= 2000 AND PROMO_COST <= 3000) OR ( PROMO_COST >= 6000 AND PROMO_COST <= 7000)
ORDER BY PROMO_CATEGORY ASC, PROMO_COST DESC;